name: build

on:
  push:
    # needs push event on default branch otherwise cache is evicted when pull request is merged
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        uses: docker/bake-action@v2
        with:
          targets: release
          set: |
            *.cache-from=type=gha,scope=build
            *.cache-to=type=gha,scope=build,mode=max

  mdl:
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Lint
        uses: docker/bake-action@v2
        with:
          targets: mdl-output
          set: |
            *.cache-to=type=gha,scope=mdl,mode=max
            *.cache-from=type=gha,scope=mdl
            *.cache-from=type=gha,scope=build
      -
        name: Annotate
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('lint/results', 'utf-8'));
            console.log(results)

            for (const result of results) {
              core.error(result.description, {
                title: result.rule + (result.aliases.length > 0 ? ` (${result.aliases[0]})` : ``),
                file: result.filename,
                startLine: result.line,
              })
            }
            if (results.length > 0) {
              process.exitCode = 1
            }

  htmlproofer:
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Lint
        uses: docker/bake-action@v2
        with:
          targets: htmlproofer-output
          set: |
            *.cache-to=type=gha,scope=htmlproofer,mode=max
            *.cache-from=type=gha,scope=htmlproofer
            *.cache-from=type=gha,scope=build
      -
        name: Annotate
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('lint/results', 'utf-8');
            console.log(results)

            const re = /^- (.+)\n  \*  (.+) \(line (\d+)\)\n(.+)$/gm;
            while (true) {
              const result = re.exec(results);
              if (result === null) {
                break;
              }

              core.error(`${result[2]}\n${result[4]}`, {
                title: 'Link check failed',
                // file: result[1],
                // startLine: result[3],
              })
            }
            if (results.length > 0) {
              process.exitCode = 1
            }

  # build-releaser job will just build _releaser app used for Netlify and
  # AWS deployment in publish workflow. it's just to be sure it builds correctly.
  build-releaser:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        uses: docker/bake-action@v2
        with:
          targets: releaser-build
          set: |
            *.cache-from=type=gha,scope=releaser
            *.cache-to=type=gha,scope=releaser,mode=max
